#!/bin/bash
#/usr/lib/check_mk_agent/local

#Get data
bgp4_sessions_up=$(birdc s p|grep BGP|grep -c up)
bgp6_sessions_up=$(birdc6 s p|grep BGP|grep -c up)
conntrack=$(conntrack -C);
conntrack_limit=$(sysctl -a |grep net.nf_conntrack_max|cut -d ' ' -f 3);
conntrack_warning=$(($conntrack_limit - 2000));

#Output
##BGP
echo "P BGP-Sessions IPv4=$bgp4_sessions_up;4:6;3:6|IPv6=$bgp6_sessions_up;4:6;3:6"
##Conntrack
echo "P Conntrack conntrack=$conntrack;$conntrack_warning;$conntrack_limit $conntrack"
