#!/bin/bash
#/usr/lib/check_mk_agent/local

#Get data
l_tunnel=$(ip a |grep l2tp|grep tunneldigger -c);
tunneldigger=$(ifconfig|grep tunneldigger -c);

#Output
echo "0 Tunneldigger Tunneldiggerbridge=$tunneldigger;1; Tunneldiggerbrücken $tunneldigger"
echo "P L2TP Clients=$l_tunnel;1:30;0:80;"


















