#!/bin/bash
#/usr/lib/check_mk_agent/plugins/ubuntu-patch

echo "<<<ubuntu-patch>>>"
if [ -x /usr/lib/update-notifier/update-motd-updates-available ]; then
    echo "Ubuntu Patch Management"
    /usr/lib/update-notifier/update-motd-updates-available
fi
if [ -x /usr/lib/update-notifier/update-motd-reboot-required ]; then
    /usr/lib/update-notifier/update-motd-reboot-required
fi
